WorkForcePro/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using WorkForcePro.Data;
using WorkForcePro.Models;
using WorkForcePro.Repositories;

namespace WorkForcePro.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyRepository _companyRepository;
        private readonly ApplicationDbContext _context;
        private readonly IEmployeeRepository _employeeRepository;
        public CompanyController(ICompanyRepository companyRepository, IEmployeeRepository employeeRepository, ApplicationDbContext dbContext)
        {
            _companyRepository = companyRepository;
            _context = dbContext;
            _employeeRepository = employeeRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Company company)
        {
            _companyRepository.Insert(company);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _companyRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            var company = _companyRepository.GetById(id);
            return View(company);
        }
        public IActionResult Edit(int id)
        {
            var company = _companyRepository.GetById(id);
            return View(company);
        }
        [HttpPost]
        public IActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                _companyRepository.Update(company);
                return RedirectToAction("Index");
            }

            return View(company);
        }
        public JsonResult ShowCompanies()
        {
            var companies = _companyRepository.GetAllItem().ToList();
            return Json(companies);
        }
    }
}

WorkForcePro/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using WorkForcePro.Models;
using WorkForcePro.Repositories;

namespace WorkForcePro.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository _DepartmentRepository;
        public DepartmentController(IDepartmentRepository repository)
        {
            _DepartmentRepository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Department department)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int ComId = Convert.ToInt32(storedCompanyId);
            department.ComId = ComId;
            _DepartmentRepository.Insert(department);
            return RedirectToAction();
        }
        public IActionResult Delete(int id)
        {
            _DepartmentRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            var department = _DepartmentRepository.GetById(id);
            return View(department);
        }
        public IActionResult Edit(int id)
        {
            var department = _DepartmentRepository.GetById(id);

            return View(department);
        }
        [HttpPost]
        public IActionResult Edit(Department depertment)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int ComId = Convert.ToInt32(storedCompanyId);
            depertment.ComId = ComId;
            _DepartmentRepository.Update(depertment);
            return RedirectToAction("Index");
        }
        public JsonResult ShowDepartment()
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var departments = _DepartmentRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            return Json(departments);
        }
    }
}

WorkForcePro/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Query.Expressions.Internal;
using System.Data;
using WorkForcePro.DtoModel;
using WorkForcePro.Models;
using WorkForcePro.Repositories;

namespace WorkForcePro.Controllers
{
    public class EmployeeController : Controller
    {
       
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly IDesignationRepository _designationRepository;
        private readonly IShiftRepository _shiftRepository;
        private readonly ICompanyRepository _companyRepository;
        private readonly ISalaryRepository _salaryRepository;
        public EmployeeController(IEmployeeRepository employeeRepository, IDepartmentRepository departmentRepository,
            IDesignationRepository designationRepository, ICompanyRepository companyRepository,
            IShiftRepository shiftRepository, ISalaryRepository salaryRepository)
        {
            _employeeRepository = employeeRepository;
            _departmentRepository = departmentRepository;
            _designationRepository = designationRepository;
            _shiftRepository = shiftRepository;
            _companyRepository = companyRepository;
            _salaryRepository = salaryRepository;
        }
        public IActionResult Index()
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var designations = _designationRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            var departments = _departmentRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            var shifts = _shiftRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            ViewData["depts"] = departments;
            ViewData["desigs"] = designations;
            ViewData["shift"] = shifts;
            return View();
        }
        [HttpPost]
        public IActionResult Index(Employee employee)
        {
            if(employee != null)
            {
                var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
                int C_id = Convert.ToInt32(storedCompanyId);
                employee.ComId = C_id;
                var company = _companyRepository.GetById(C_id);
                if (employee.DtJoin.HasValue && employee.DtJoin.Value.Kind == DateTimeKind.Unspecified)
                {
                    employee.DtJoin = DateTime.SpecifyKind(employee.DtJoin.Value, DateTimeKind.Utc);
                }
                // Calculate Basic based on Gross and division
                double division = ((double)company.Basic) / 100.00;
                employee.Basic = (int?)(employee.Gross * division);

                division = ((double)company.HRent) / 100.00;
                // Calculate HRent based on Gross and company.HRent
                employee.HRent = (int?)(employee.Gross * division);

                division = ((double)company.Medical) / 100.00;
                // Calculate Medical based on Gross and company.Medical
                employee.Medical = (int?)(employee.Gross * division);

                // Insert the employee into the repository
                _employeeRepository.Insert(employee);

            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _employeeRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            var employee = _employeeRepository.GetById(id);
            return View(employee);
        }
        public IActionResult Edit(int id)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var designations = _designationRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            var departments = _departmentRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            var shifts = _shiftRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            ViewData["depts"] = departments;
            ViewData["desigs"] = designations;
            ViewData["shift"] = shifts;
            var employee = _employeeRepository.GetById(id);
            return View(employee);
        }
        [HttpPost]
        public IActionResult Edit(Employee employee)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int ComId = Convert.ToInt32(storedCompanyId);
            employee.ComId = ComId;
            _employeeRepository.Update(employee);
            return RedirectToAction("Index");
        }
        public IActionResult ShowEmployee()
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var empList = _employeeRepository.GetAllInItem(C_id);
            return Json(empList);
        }
        public IActionResult ProcessAll()
        {
            // Replace these values with your actual PostgreSQL connection string
            string connectionString = "Server=localhost;Port=5432;Username=postgres;Password=orpit23arfatur;Database=WorkForcePro;";

            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int comId = Convert.ToInt32(storedCompanyId);
            // Replace these values with the actual parameters for your function
            DateTime dateTime = DateTime.Now;
            int month = dateTime.Month;
            int year = dateTime.Year;

            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();

                using (NpgsqlCommand cmd = new NpgsqlCommand("public.attendanceandsummary", connection))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Add parameters to the command
                    cmd.Parameters.AddWithValue("in_comid", comId);
                    cmd.Parameters.AddWithValue("in_month", month);
                    cmd.Parameters.AddWithValue("in_year", year);

                    List <SalaryViewModel> employeeSummaries = new List<SalaryViewModel>();

                    using (NpgsqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            SalaryViewModel employeeSummary = new SalaryViewModel
                            {
                                EmpId = reader.GetInt32(0),
                                ComId = reader.GetInt32(1),
                                DtYear = reader.GetInt32(2),
                                DtMonth = reader.GetInt32(3),
                                Present = reader.GetInt32(4),
                                Late = reader.GetInt32(5),
                                Absent = reader.GetInt32(6),
                                Gross = reader.GetDecimal(7),
                                Basic = reader.GetDecimal(8),
                                HRent = reader.GetDecimal(9),
                                Medical = reader.GetDecimal(10),
                                AbsentAmount = reader.GetDecimal(11),
                                PayableAmount = reader.GetDecimal(12),
                                IsPaid = reader.GetBoolean(13)
                            };
                            employeeSummary.MonthName = new DateTime(1, employeeSummary.DtMonth, 1).ToString("MMMM");
                            Employee employee = _employeeRepository.GetById(employeeSummary.EmpId);
                            employeeSummary.EmpCode = employee.EmpCode;
                            employeeSummary.EmpName = employee.EmpName;
                            employeeSummary.DeptName = _departmentRepository.GetById(employee.DeptId).DeptName;
                            employeeSummary.DesigName =_designationRepository.GetById(employee.DesigId).DesigName;
                            employeeSummaries.Add(employeeSummary);
                        }
                    }
                    if(employeeSummaries != null)
                    {
                        return View(employeeSummaries);
                    }
                }
                return View();
            }
        }
        
        public IActionResult ShowEmployeeByDepartment()
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var empList = _employeeRepository.GetAllInItem(C_id);
            var departments = _departmentRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            ViewData["depts"] = departments;
            return View();
        }
        [HttpPost]
        public IActionResult EmployeeByDepartment(int DeptId)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var employeeList = _employeeRepository.GetAllByDept(C_id, DeptId).ToList();
            return Json(employeeList);
        }

    }
}

WorkForcePro/Controllers/ShiftController.cs
using Microsoft.AspNetCore.Mvc;
using WorkForcePro.Models;
using WorkForcePro.Repositories;

namespace WorkForcePro.Controllers
{
    public class ShiftController : Controller
    {
        private readonly IShiftRepository _shiftRepository;
        public ShiftController(IShiftRepository shiftRepository)
        {
            _shiftRepository = shiftRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Shift shift)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int ComId = Convert.ToInt32(storedCompanyId);
            shift.ComId = ComId;
            _shiftRepository.Insert(shift);
            return RedirectToAction();
        }
        public IActionResult Delete(int id)
        {
            _shiftRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            var shift = _shiftRepository.GetById(id);
            return View(shift);
        }
        public IActionResult Edit(int id)
        {
            var shift = _shiftRepository.GetById(id);

            return View(shift);
        }
        [HttpPost]
        public IActionResult Edit(Shift shift)
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int ComId = Convert.ToInt32(storedCompanyId);
            shift.ComId = ComId;
            _shiftRepository.Update(shift);
            return RedirectToAction("Index");
        }
        public JsonResult ShowShift()
        {
            var storedCompanyId = Request.Cookies["SelectedCompanyId"].ToString();
            int C_id = Convert.ToInt32(storedCompanyId);
            var shift = _shiftRepository.GetAllItem().Where(x => x.ComId == C_id).ToList();
            return Json(shift);
        }
    }
}

WorkForcePro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkForcePro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkForcePro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkForcePro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Request.Cookies["SelectedCompanyName"] == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Companies</a>
                            </li>
                        }
                        @if (Context.Request.Cookies["SelectedCompanyName"] != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Deparments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Designation" asp-action="Index">Designations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shift" asp-action="Index">Shifts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="ShowEmployeeByDepartment">Search Employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="ProcessAll">ProcessAll</a>
                            </li>
                            <!-- Display company name in the navbar if available -->
                            <li class="nav-item" id="selectedCompanyNavItem" style="display: none;">
                                <span class="nav-link text-dark" id="selectedCompanyNavbar"></span>
                            </li>
                            <!-- Display logout button if company is selected -->
                            <li class="nav-item" id="logoutNavItem" style="display: none;">
                                <a class="nav-link text-dark" id="logoutButton" style="cursor: pointer;">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WorkForcePro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        // Check if a company is selected
        var isCompanySelected = @(Context.Request.Cookies["SelectedCompanyId"] != null ? "true" : "false");

        // Update the visibility of the selected company name and logout button
        if (isCompanySelected) {
            $('#selectedCompanyNavItem').show();
            $('#logoutNavItem').show();
            var selectedCompanyName = '@Context.Request.Cookies["SelectedCompanyName"]';
            $('#selectedCompanyNavbar').text('Selected Company: ' + selectedCompanyName);
        }

        // Handle logout button click
        $('#logoutButton').click(function () {
            // Clear the selected company in the navbar
            $('#selectedCompanyNavItem').hide();
            $('#logoutNavItem').hide();
            $('#selectedCompanyNavbar').text('');

            // Clear the cookie by sending a request to the backend
            $.ajax({
                url: '/Home/Logout',
                method: 'POST',
                success: function (response) {
                    console.log("Logout response:", response);
                    // You can add additional logic here if needed
                },
                error: function (error) {
                    console.error("Logout error:", error);
                }
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>